/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java`
    `checkstyle`
    id("org.springframework.boot") version "2.7.2"
    id("io.freefair.lombok") version "6.5.0.3"
}

apply(plugin = "io.spring.dependency-management")

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-data-mongodb")
    implementation("org.springframework.boot:spring-boot-starter-security")
    implementation("org.springframework.boot:spring-boot-starter-validation")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("junit:junit:4.13.2")
    testImplementation("org.testcontainers:mongodb:1.17.3")
    compileOnly("org.projectlombok:lombok:1.18.24")
    compileOnly("org.apache.maven.plugins:maven-surefire-plugin:2.22.2")
}

tasks.create<Exec>("import-sample-data") {
    workingDir("../sample-data")
    commandLine("./import.sh")
}

tasks.create<Exec>("import-sample-data-docker") {
    workingDir("../sample-data")
    commandLine("./import.sh", "docker")
}

group = "com.starter"
version = "0.0.1-SNAPSHOT"
description = "starter-fullstack"
java.sourceCompatibility = JavaVersion.VERSION_11
